{
 "title": "Telemetry Playground",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "NE",
    "query": {
     "query": "label_values({namespace_name=\"$namespace\"},node_name)"
    }
   },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   },
   {
    "name": "Logs",
    "query": {}
   },
   { "name": "cleared_status", "query": "true, false" },
   {
    "name": "NE_top",
    "query": {
     "query": "label_values({namespace_name=\"$namespace\"},node_name)"
    }
   },
   { "name": "namespace", "label": "namespace", "query": "eda-telemetry" },
   {
    "name": "syslog_app",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "DC Fabric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric Health",
   "type": "heatmap",
   "description": "Fabric's health score",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "resources_cr_fabrics_eda_nokia_com_v1_fabric_status_health{namespace_name='$namespace'}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Network Telemetry",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 18, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "node_srl_interface_oper_state{namespace_name='$namespace'}",
     "legendFormat": "oper-state:{{node_name}}:{{interface_name}}"
    },
    {
     "expr": "last_over_time(node_srl_interface_traffic_rate_out_bps{namespace_name='$namespace'}[20s])",
     "legendFormat": "{{node_name}}:{{interface_name}}:out"
    },
    {
     "expr": "last_over_time(node_srl_interface_traffic_rate_in_bps{namespace_name='$namespace'}[20s])",
     "legendFormat": "{{node_name}}:{{interface_name}}:in"
    }
   ]
  },
  {
   "title": "Services",
   "type": "state-timeline",
   "description": "Operational state of the services",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "resources_cr_services_eda_nokia_com_v2_virtualnetwork_status_operationalState{namespace_name='$namespace'}",
     "legendFormat": " {{virtualnetwork_name}}"
    }
   ]
  },
  {
   "title": "BGP Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resources_cr_protocols_eda_nokia_com_v2_defaultbgpgroup_status_numPeers{namespace_name='$namespace'} - resources_cr_protocols_eda_nokia_com_v2_defaultbgpgroup_status_numPeersOperDown{namespace_name='$namespace'}",
     "legendFormat": "Oper Up"
    },
    {
     "expr": "resources_cr_protocols_eda_nokia_com_v2_defaultbgpgroup_status_numPeers{namespace_name='$namespace'}",
     "legendFormat": "Total Peers"
    }
   ]
  },
  {
   "title": "Interfaces Health",
   "type": "timeseries",
   "description": "1h average uptime measured as a %",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "avg(\n  (node_srl_interface_oper_state{node_name=~\"leaf.+\",interface_name=~\"ethernet-1/(1|2|49|50)\",namespace_name=\"$namespace\"} == bool 1)\n* on (node_name, interface_name)\n  (node_srl_interface_admin_state{node_name=~\"leaf.+\",interface_name=~\"ethernet-1/(1|2|49|50)\",namespace_name=\"$namespace\"} == bool 1)\n) * 100",
     "legendFormat": "health %"
    }
   ]
  },
  {
   "title": "Node Selection",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 12, "w": 2, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "node_srl_interface_traffic_rate_in_bps{node_name=~'$NE_top', namespace_name='$namespace'}",
     "legendFormat": "{{node_name}}:{{interface_name}}:in"
    },
    {
     "expr": "node_srl_interface_traffic_rate_out_bps{node_name=~'$NE_top', namespace_name='$namespace'}",
     "legendFormat": "{{node_name}}:{{interface_name}}:out"
    }
   ]
  },
  {
   "title": "Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(node_srl_interface_traffic_rate_in_bps)",
     "legendFormat": "in"
    },
    {
     "expr": "sum(node_srl_interface_traffic_rate_out_bps)",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Default VRF Health",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resources_cr_routing_eda_nokia_com_v1_defaultrouter_status_health{namespace_name='$namespace'}",
     "legendFormat": "{{defaultrouter_name}}"
    }
   ]
  },
  { "title": "EDA Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Alarms",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"kafka-alarms\", namespace_name=\"$namespace\"} | json"
    }
   ]
  },
  {
   "title": "Deviations over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({component=\"kafka-deviations\", namespace_name=\"$namespace\"} | json | keep spec_nodeEndpoint [1m]  )"
    }
   ]
  },
  {
   "title": "Alarms over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({component=\"kafka-alarms\", namespace_name=\"$namespace\"} | json| keep type [1m])"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{component=\"kafka-alarms\", namespace_name=\"$namespace\"} | json | line_format \"{{if eq .cleared \\\"true\\\"}}-- CLEARED -- {{end}}Severity: {{.severity}} Name: {{.alarm_name}} Description: {{.description}}\""
    }
   ]
  },
  {
   "title": "Deviations",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"kafka-deviations\", namespace_name=\"$namespace\"} | json | line_format \"Deviation detected on {{.spec_nodeEndpoint}} {{.spec_path}}\""
    }
   ]
  },
  { "title": "$NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Node",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_srl_platform_control_memory_free{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Free "
    },
    {
     "expr": "node_srl_platform_control_memory_utilization{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "node_srl_platform_control_memory_reserved{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "node_srl_platform_control_memory_physical{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_srl_interface_traffic_rate_in_bps{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "node_srl_interface_traffic_rate_out_bps{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_srl_network_instance_protocols_bgp_statistics_up_peers{network_instance_name=\"default\",node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "node_srl_network_instance_protocols_bgp_statistics_total_peers{network_instance_name=\"default\",node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "node_srl_network_instance_protocols_bgp_statistics_disabled_peers{network_instance_name=\"default\",node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Disabled Peers"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_srl_network_instance_protocols_bgp_statistics_total_active_routes{network_instance_name=\"default\",node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Total Active Routes"
    },
    {
     "expr": "node_srl_network_instance_protocols_bgp_statistics_total_received_routes{network_instance_name=\"default\",node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Total Received Routes"
    }
   ]
  },
  {
   "title": "Running SR Linux applications",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
   "targets": [
    {
     "expr": "node_srl_system_app_management_application_pid{node_name='$NE', namespace_name='$namespace'}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_srl_network_instance_route_table_ipv4_unicast_statistics_active_routes{network_instance_name=\"default\",node_name=\"$NE\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "node_srl_network_instance_route_table_ipv4_unicast_statistics_total_routes{network_instance_name=\"default\",node_name=\"$NE\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {
     "expr": "node_srl_network_instance_route_table_ipv4_unicast_statistics_active_routes_with_ecmp{network_instance_name=\"default\",node_name=\"$NE\"}",
     "legendFormat": "IPv4 Active ECMP Routes"
    }
   ]
  },
  {
   "title": "Services",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 70 },
   "targets": [
    {
     "expr": "node_srl_network_instance_oper_state{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "{{ network_instance_name}}"
    }
   ]
  },
  {
   "title": "Port Oper State",
   "type": "status-history",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "node_srl_interface_oper_state{node_name=\"$NE\", namespace_name=\"$namespace\"}\n  * on(interface_name, node_name, namespace_name)\n    (node_srl_interface_admin_state{node_name=\"$NE\", namespace_name=\"$namespace\"} == 1)",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_srl_platform_control_cpu_total_instant{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Syslog $NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Node",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log:",
   "type": "logs",
   "gridPos": { "h": 13, "w": 14, "x": 3, "y": 87 },
   "targets": [
    {
     "expr": "{source=\"$NE\", application=~\"$syslog_app\"}"
    }
   ]
  },
  {
   "title": "Total logs $NE",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (count_over_time({source=\"$NE\", application=~\"$syslog_app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Syslog App",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 90 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log volume:",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({source=\"$NE\", application=~\"$syslog_app\"} | logfmt [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}