apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: apps
  namespace: eda-system
spec:
  exports:
    - metricName:
        regex: namespace_(.+)
        replacement: $1
      path: .namespace.node.srl.system.app-management.application

---
apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: bgp-stats
  namespace: eda-system
spec:
  exports:
    - metricName:
        regex: namespace_(.+)
        replacement: $1
      path: .namespace.node.srl.network-instance.protocols.bgp.statistics

---
apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: cpu
  namespace: eda-system
spec:
  exports:
    - metricName:
        regex: namespace_(.+)
        replacement: $1
      path: .namespace.node.srl.platform.control.cpu.total

---
apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: default-bgp-group-status
  namespace: eda-system
spec:
  exports:
    - metricName:
        regex: namespace_(.+)
        replacement: $1
      path: >-
        .namespace.resources.cr-status.protocols_eda_nokia_com.v1alpha1.defaultbgpgroup.status

---
apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: default-router-status
  namespace: eda-system
spec:
  exports:
    - metricName:
        regex: namespace_(.+)
        replacement: $1
      path: >-
        .namespace.resources.cr-status.routing_eda_nokia_com.v1alpha1.defaultrouter.status

---
apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: interface
  namespace: eda-system
spec:
  exports:
    - mappings:
        - destination: "1"
          source: up
        - destination: "0"
          source: down
      metricName:
        regex: namespace_(.+)
        replacement: $1
      path: .namespace.node.srl.interface

---
apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: interface-traffic-rate
  namespace: eda-system
spec:
  exports:
    - metricName:
        regex: namespace_(.+)
        replacement: $1
      path: .namespace.node.srl.interface.traffic-rate

---
apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: memory
  namespace: eda-system
spec:
  exports:
    - metricName:
        regex: namespace_(.+)
        replacement: $1
      path: .namespace.node.srl.platform.control.memory

---
apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: network-instance
  namespace: eda-system
spec:
  exports:
    - mappings:
        - destination: "1"
          source: up
        - destination: "0"
          source: down
      metricName:
        regex: namespace_(.+)
        replacement: $1
      path: .namespace.node.srl.network-instance

---
apiVersion: prom.eda.nokia.com/v1alpha1
kind: Export
metadata:
  name: ipv4-statistics
  namespace: eda-system
spec:
  exports:
    - metricName:
        regex: namespace_(.+)
        replacement: $1
      path: .namespace.node.srl.network-instance.route-table.ipv4-unicast.statistics
