apiVersion: fabrics.eda.nokia.com/v1alpha1
kind: Fabric
metadata:
  name: fabric
  namespace: clab-eda-st
spec:
  leafs:
    leafNodeSelector:
      - eda.nokia.com/role=leaf
  spines:
    spineNodeSelector:
      - eda.nokia.com/role=spine
  interSwitchLinks:
    unnumbered: IPV6
    linkSelector:
      - eda.nokia.com/role=interSwitch
  underlayProtocol:
    bfd:
      enabled: true
    bgp:
      asnPool: asn-pool
      timers:
        connectRetry: 10
        holdTime: 3
        keepAlive: 1
        minimumAdvertisementInterval: 1
    protocol:
      - EBGP
  overlayProtocol:
    bfd:
      enabled: true
    bgp:
      autonomousSystem: 65100
      clusterID: "100"
      rrClientNodeSelector:
        - eda.nokia.com/role=leaf
      rrNodeSelector:
        - eda.nokia.com/role=spine
      timers:
        connectRetry: 10
        holdTime: 3
        keepAlive: 1
        minimumAdvertisementInterval: 1
    protocol: IBGP
  systemPoolIPV4: systemipv4-pool
