apiVersion: services.eda.nokia.com/v1alpha1
kind: VirtualNetwork
metadata:
  name: ipvrf2001
  namespace: clab-eda-st
spec:
  bridgeDomains:
    - name: macvrf201
      spec:
        eviPool: evi-pool
        macDuplicationDetection:
          enabled: true
        tunnelIndexPool: tunnel-index-pool
        vniPool: vni-pool
        macLimit: 250
    - name: macvrf202
      spec:
        eviPool: evi-pool
        macDuplicationDetection:
          enabled: true
        tunnelIndexPool: tunnel-index-pool
        vniPool: vni-pool
        macLimit: 250
  irbInterfaces:
    - name: macvrf201-irb
      spec:
        bridgeDomain: macvrf201
        ipAddresses:
          - ipv4Address:
              ipPrefix: 10.20.1.254/24
              primary: false
        router: ipvrf2001
    - name: macvrf202-irb
      spec:
        bridgeDomain: macvrf202
        ipAddresses:
          - ipv4Address:
              ipPrefix: 10.20.2.254/24
              primary: false
        router: ipvrf2001
  routers:
    - name: ipvrf2001
      spec:
        eviPool: evi-pool
        routerID: "2001"
        tunnelIndexPool: tunnel-index-pool
        vniPool: vni-pool
  vlans:
    - name: macvrf201
      spec:
        bridgeDomain: macvrf201
        interfaceSelector:
          - eda.nokia.com/macvrf201
        vlanID: "201"
    - name: macvrf202
      spec:
        bridgeDomain: macvrf202
        interfaceSelector:
          - eda.nokia.com/macvrf202
        vlanID: "202"
