apiVersion: services.eda.nokia.com/v1alpha1
kind: VirtualNetwork
metadata:
  name: macvrf1001
  namespace: clab-eda-st
spec:
  bridgeDomains:
    - name: macvrf1001
      spec:
        eviPool: evi-pool
        l2proxyARPND:
          proxyARP: false
          proxyND: false
        macAging: 300
        macDuplicationDetection:
          action: StopLearning
          enabled: true
          holdDownTime: 9
          monitoringWindow: 3
          numMoves: 5
        tunnelIndexPool: tunnel-index-pool
        vniPool: vni-pool
        macLimit: 250
  vlans:
    - name: macvrf1001
      spec:
        bridgeDomain: macvrf1001
        interfaceSelector:
          - eda.nokia.com/macvrf1001
        vlanID: "1001"
