apiVersion: core.eda.nokia.com/v1
kind: NodeUser
metadata:
  name: admin
  namespace: clab-eda-st
spec:
  username: admin
  password: eda124!
  groupBindings:
    - groups:
        - sudo
      nodeSelector:
        - ''
  sshPublicKeys:
    []