apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine1-e1-1-leaf1-e1-49
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-1
        interfaceResource: spine1-ethernet-1-1
        node: spine1
      remote:
        interface: ethernet-1-49
        interfaceResource: leaf1-ethernet-1-49
        node: leaf1
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine2-e1-1-leaf1-e1-50
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-1
        interfaceResource: spine2-ethernet-1-1
        node: spine2
      remote:
        interface: ethernet-1-50
        interfaceResource: leaf1-ethernet-1-50
        node: leaf1
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine1-e1-2-leaf2-e1-49
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-2
        interfaceResource: spine1-ethernet-1-2
        node: spine1
      remote:
        interface: ethernet-1-49
        interfaceResource: leaf2-ethernet-1-49
        node: leaf2
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine2-e1-2-leaf2-e1-50
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-2
        interfaceResource: spine2-ethernet-1-2
        node: spine2
      remote:
        interface: ethernet-1-50
        interfaceResource: leaf2-ethernet-1-50
        node: leaf2
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine1-e1-3-leaf3-e1-49
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-3
        interfaceResource: spine1-ethernet-1-3
        node: spine1
      remote:
        interface: ethernet-1-49
        interfaceResource: leaf3-ethernet-1-49
        node: leaf3
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine2-e1-3-leaf3-e1-50
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-3
        interfaceResource: spine2-ethernet-1-3
        node: spine2
      remote:
        interface: ethernet-1-50
        interfaceResource: leaf3-ethernet-1-50
        node: leaf3
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine1-e1-4-leaf4-e1-49
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-4
        interfaceResource: spine1-ethernet-1-4
        node: spine1
      remote:
        interface: ethernet-1-49
        interfaceResource: leaf4-ethernet-1-49
        node: leaf4
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: spine2-e1-4-leaf4-e1-50
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-4
        interfaceResource: spine2-ethernet-1-4
        node: spine2
      remote:
        interface: ethernet-1-50
        interfaceResource: leaf4-ethernet-1-50
        node: leaf4
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  generation: 1
  labels:
    eda.nokia.com/macvrf201: 'true'
    eda.nokia.com/macvrf1001: 'true'
    eda.nokia.com/role: edge
  name: l1-l2-eth-1-1-lag-1
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-1
        interfaceResource: leaf1-ethernet-1-1
        node: leaf1
      speed: 10G
      type: edge
    - local:
        interface: ethernet-1-1
        interfaceResource: leaf2-ethernet-1-1
        node: leaf2
      speed: 10G
      type: edge
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  generation: 1
  labels:
    eda.nokia.com/macvrf202: 'true'
    eda.nokia.com/macvrf1001: 'true'
    eda.nokia.com/role: edge
  name: l1-l2-eth-1-2-lag-2
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-2
        interfaceResource: leaf1-ethernet-1-2
        node: leaf1
      speed: 10G
      type: edge
    - local:
        interface: ethernet-1-2
        interfaceResource: leaf2-ethernet-1-2
        node: leaf2
      speed: 10G
      type: edge
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  generation: 1
  labels:
    eda.nokia.com/macvrf201: 'true'
    eda.nokia.com/macvrf1001: 'true'
    eda.nokia.com/role: edge
  name: l3-l4-eth-1-1-lag-3
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-1
        interfaceResource: leaf3-ethernet-1-1
        node: leaf3
      speed: 10G
      type: edge
    - local:
        interface: ethernet-1-1
        interfaceResource: leaf4-ethernet-1-1
        node: leaf4
      speed: 10G
      type: edge
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  generation: 1
  labels:
    eda.nokia.com/macvrf202: 'true'
    eda.nokia.com/macvrf1001: 'true'
    eda.nokia.com/role: edge
  name: l3-l4-eth-1-2-lag-4
  namespace: clab-eda-st
spec:
  links:
    - local:
        interface: ethernet-1-2
        interfaceResource: leaf3-ethernet-1-2
        node: leaf3
      speed: 10G
      type: edge
    - local:
        interface: ethernet-1-2
        interfaceResource: leaf4-ethernet-1-2
        node: leaf4
      speed: 10G
      type: edge