apiVersion: services.eda.nokia.com/v1
kind: VirtualNetwork
metadata:
  name: ipvrf2001
  namespace: eda-telemetry
spec:
  bridgeDomains:
    - name: macvrf201
      spec:
        eviPool: evi-pool
        macAging: 300
        macLearning: true
        macLimit: 250
        tunnelIndexPool: tunnel-index-pool
        type: EVPNVXLAN
        vniPool: vni-pool
    - name: macvrf202
      spec:
        eviPool: evi-pool
        tunnelIndexPool: tunnel-index-pool
        type: EVPNVXLAN
        vniPool: vni-pool
  irbInterfaces:
    - name: macvrf201-irb
      spec:
        bridgeDomain: macvrf201
        ipAddresses:
          - ipv4Address:
              ipPrefix: 10.20.1.254/24
              primary: false
        ipMTU: 9394
        router: ipvrf2001
    - name: macvrf202-irb
      spec:
        bridgeDomain: macvrf202
        ipAddresses:
          - ipv4Address:
              ipPrefix: 10.20.2.254/24
              primary: false
        ipMTU: 9394
        router: ipvrf2001
  routers:
    - name: ipvrf2001
      spec:
        eviPool: evi-pool
        routerID: "2001"
        tunnelIndexPool: tunnel-index-pool
        type: EVPNVXLAN
        vniPool: vni-pool
  vlans:
    - name: macvrf201
      spec:
        bridgeDomain: macvrf201
        interfaceSelector:
          - eda.nokia.com/macvrf201
        vlanID: "201"
    - name: macvrf202
      spec:
        bridgeDomain: macvrf202
        interfaceSelector:
          - eda.nokia.com/macvrf202
        vlanID: "202"
