apiVersion: services.eda.nokia.com/v1
kind: VirtualNetwork
metadata:
  name: macvrf1001
  namespace: eda-telemetry
spec:
  bridgeDomains:
    - name: macvrf1001
      spec:
        eviPool: evi-pool
        macAging: 300
        macLearning: true
        tunnelIndexPool: tunnel-index-pool
        type: EVPNVXLAN
        vniPool: vni-pool
  vlans:
    - name: macvrf1001
      spec:
        bridgeDomain: macvrf1001
        interfaceSelector:
          - eda.nokia.com/macvrf1001
        vlanID: "1001"
