{
 "title": "Telemetry Playground",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(node_name)" } },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   },
   {
    "name": "Logs",
    "query": {}
   },
   { "name": "cleared_status", "query": "true, false" },
   { "name": "NE_top", "query": { "query": "label_values(node_name)" } },
   { "name": "namespace", "label": "namespace", "query": "clab-eda-st" },
   {
    "name": "syslog_app",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "DC Fabric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Node Selection", "type": "volkovlabs-variable-panel", "gridPos": { "h": 11, "w": 2, "x": 0, "y": 1 } },
  {
   "title": "DC Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "node_srl_interface_traffic_rate_in_bps{node_name=~'$NE_top', namespace_name='$namespace'}",
     "legendFormat": "{{node_name}}:{{interface_name}}:in"
    },
    {
     "expr": "node_srl_interface_traffic_rate_out_bps{node_name=~'$NE_top', namespace_name='$namespace'}",
     "legendFormat": "{{node_name}}:{{interface_name}}:out"
    }
   ]
  },
  {
   "title": "Network Telemetry",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 21, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "node_srl_interface_oper_state{namespace_name='$namespace'}",
     "legendFormat": "oper-state:{{node_name}}:{{interface_name}}"
    },
    {
     "expr": "last_over_time(node_srl_interface_traffic_rate_out_bps{namespace_name='$namespace'}[20s])",
     "legendFormat": "{{node_name}}:{{interface_name}}:out"
    },
    {
     "expr": "last_over_time(node_srl_interface_traffic_rate_in_bps{namespace_name='$namespace'}[20s])",
     "legendFormat": "{{node_name}}:{{interface_name}}:in"
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resources_cr_status_routing_eda_nokia_com_v1alpha1_defaultrouter_status_health{namespace_name='$namespace'}",
     "legendFormat": "{{defaultrouter_name}}"
    }
   ]
  },
  {
   "title": "Number of BGP peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resources_cr_status_protocols_eda_nokia_com_v1alpha1_defaultbgpgroup_status_numPeers{namespace_name='$namespace'} - on(namespace_name, instance, job, defaultbgpgroup_name) resources_cr_status_protocols_eda_nokia_com_v1alpha1_defaultbgpgroup_status_numPeersOperDown{namespace_name='$namespace'}",
     "legendFormat": "{{defaultbgpgroup_name}}"
    }
   ]
  },
  { "title": "EDA Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Alarms",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{component=\"kafka-alarms\", namespace_name=\"clab-eda-st\"} | json"
    }
   ]
  },
  {
   "title": "Deviations over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 23 },
   "targets": [
    {
     "expr": "count_over_time({component=\"kafka-deviations\", namespace_name=\"clab-eda-st\"} | json | keep spec_nodeEndpoint [1m]  )"
    }
   ]
  },
  {
   "title": "Alarms over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({component=\"kafka-alarms\", namespace_name=\"clab-eda-st\"} | json| keep type [1m])"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{component=\"kafka-alarms\", namespace_name=\"clab-eda-st\"} | json | line_format \"{{if eq .cleared \\\"true\\\"}}-- CLEARED -- {{end}}Severity: {{.severity}} Name: {{.alarm_name}} Description: {{.description}}\""
    }
   ]
  },
  {
   "title": "Deviations",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{component=\"kafka-deviations\", namespace_name=\"clab-eda-st\"} | json | line_format \"Deviation detected on {{.spec_nodeEndpoint}} {{.spec_path}}\""
    }
   ]
  },
  { "title": "$NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  { "title": "Node", "type": "volkovlabs-variable-panel", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 48 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_srl_platform_control_memory_free{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Free "
    },
    {
     "expr": "node_srl_platform_control_memory_utilization{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "node_srl_platform_control_memory_reserved{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "node_srl_platform_control_memory_physical{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_srl_interface_traffic_rate_in_bps{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "node_srl_interface_traffic_rate_out_bps{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_srl_network_instance_protocols_bgp_statistics_up_peers{network_instance_name=\"default\",node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "node_srl_network_instance_protocols_bgp_statistics_total_peers{network_instance_name=\"default\",node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_disabled_peers{network_instance_name=\"default\",source=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Disabled Peers"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_srl_network_instance_protocols_bgp_statistics_total_received_routes{network_instance_name=\"default\",node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "node_srl_network_instance_protocols_bgp_statistics_total_active_routes{network_instance_name=\"default\",node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Total Active Routes"
    }
   ]
  },
  {
   "title": "Running SR Linux applications",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
   "targets": [
    {
     "expr": "node_srl_system_app_management_application_pid{node_name='$NE', namespace_name='$namespace'}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_srl_network_instance_route_table_ipv4_unicast_statistics_active_routes{network_instance_name=\"default\",node_name=\"$NE\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "node_srl_network_instance_route_table_ipv4_unicast_statistics_total_routes{network_instance_name=\"default\",node_name=\"$NE\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {
     "expr": "node_srl_network_instance_route_table_ipv4_unicast_statistics_active_routes_with_ecmp{network_instance_name=\"default\",node_name=\"$NE\"}",
     "legendFormat": "IPv4 Active ECMP Routes"
    }
   ]
  },
  {
   "title": "Services",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "targets": [
    {
     "expr": "node_srl_network_instance_oper_state{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "{{ network_instance_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_srl_platform_control_cpu_total_instant{node_name=\"$NE\", namespace_name='$namespace'}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Syslog $NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  { "title": "Node", "type": "volkovlabs-variable-panel", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 73 } },
  {
   "title": "Log:",
   "type": "logs",
   "gridPos": { "h": 13, "w": 14, "x": 3, "y": 73 },
   "targets": [
    {
     "expr": "{source=\"$NE\", application=~\"$syslog_app\"}"
    }
   ]
  },
  {
   "title": "Total logs $NE",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (count_over_time({source=\"$NE\", application=~\"$syslog_app\"}[$__range]))"
    }
   ]
  },
  { "title": "Syslog App", "type": "volkovlabs-variable-panel", "gridPos": { "h": 10, "w": 3, "x": 0, "y": 76 } },
  {
   "title": "Log volume:",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({source=\"$NE\", application=~\"$syslog_app\"} | logfmt [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}