apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: telemetry-stack
data:
  prometheus.yml: |-
    {{- .Files.Get "files/prometheus/prometheus.yml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    app: telemetry-stack
data:
  datasource.yml: |-
    {{- .Files.Get "files/grafana/datasource.yml" | nindent 4 }}
  dashboards.yml: |-
    {{- .Files.Get "files/grafana/dashboards.yml" | nindent 4 }}
  st.json: |-
    {{- .Files.Get "files/grafana/dashboards/st.json" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  labels:
    app: telemetry-stack
data:
  promtail-config.yml: |-
    {{- .Files.Get "files/promtail/promtail-config.yml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    app: telemetry-stack
data:
  loki-config.yml: |-
    {{- .Files.Get "files/loki/loki-config.yml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  labels:
    app: telemetry-stack
data:
  config.alloy: |-
    {{- .Files.Get "files/alloy/config.alloy" | nindent 4 }}
