replicaCount: 1
imagePullPolicy: IfNotPresent
eda_url: "docs.eda.dev" # no schema and port here, just the domain name or IP address

# Grafana persistence configuration
grafana:
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
    annotations: {}

# Prometheus persistence configuration
prometheus:
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 3Gi
    annotations: {}
