replicaCount: 1
imagePullPolicy: IfNotPresent
eda_url: "https://changeme.eda.dev:443" # the domain name or IP address with port number if needed

# Grafana persistence configuration
grafana:
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
    annotations: {}

# Prometheus persistence configuration
prometheus:
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 3Gi
    annotations: {}
