spec:
  kubernetes:
    exports:
      - gvk:
          group: protocols.eda.nokia.com
          kind: DefaultBGPGroup
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: DefaultBGPGroupDeployment
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: BGPGroup
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: BGPGroupDeployment
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: DefaultRouteReflector
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: DefaultRouteReflectorClient
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: RouteReflector
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: RouteReflectorState
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: RouteReflectorClientState
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: RouteReflectorClient
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: DefaultBGPPeer
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: BGPPeer
          version: v1alpha1
        policy: all
      - gvk:
          group: protocols.eda.nokia.com
          kind: BGPPeerState
          version: v1alpha1
        policy: all
      - gvk:
          group: fabrics.eda.nokia.com
          kind: ISL
          version: v1alpha1
        policy: all
      - gvk:
          group: fabrics.eda.nokia.com
          kind: ISLState
          version: v1alpha1
        policy: all
      - gvk:
          group: routing.eda.nokia.com
          kind: DefaultInterface
          version: v1alpha1
        policy: all
      - gvk:
          group: routing.eda.nokia.com
          kind: DefaultInterfaceState
          version: v1alpha1
        policy: all
      - gvk:
          group: routingpolicies.eda.nokia.com
          kind: Policy
          version: v1alpha1
        policy: all
      - gvk:
          group: routingpolicies.eda.nokia.com
          kind: PolicyDeployment
          version: v1alpha1
        policy: all
      - gvk:
          group: routingpolicies.eda.nokia.com
          kind: PrefixSet
          version: v1alpha1
        policy: all
      - gvk:
          group: routingpolicies.eda.nokia.com
          kind: PrefixSetDeployment
          version: v1alpha1
        policy: all
      - gvk:
          group: services.eda.nokia.com
          kind: IRBInterface
          version: v1alpha1
        policy: all
      - gvk:
          group: services.eda.nokia.com
          kind: RoutedInterface
          version: v1alpha1
        policy: all
      - gvk:
          group: services.eda.nokia.com
          kind: BridgeDomain
          version: v1alpha1
        policy: all
      - gvk:
          group: services.eda.nokia.com
          kind: BridgeDomainDeployment
          version: v1alpha1
        policy: all
      - gvk:
          group: services.eda.nokia.com
          kind: BridgedInterface
          version: v1alpha1
        policy: all
      - gvk:
          group: services.eda.nokia.com
          kind: Router
          version: v1alpha1
        policy: all
      - gvk:
          group: services.eda.nokia.com
          kind: RouterDeployment
          version: v1alpha1
        policy: all
      - gvk:
          group: services.eda.nokia.com
          kind: VLAN
          version: v1alpha1
        policy: all
